sudo: required
services:
  - docker

before_install:
  - docker build -t pepperoniblvd/react-test -f ./client/Dockerfile.dev

scripts:
  - docker run -e CI=true pepperoniblvd/react-test npm test

after_success:
  - docker build -t pepperoniblvd/multi-client ./client
  - docker build -t pepperoniblvd/multi-nginx ./nginx
  - docker build -t pepperoniblvd/multi-server ./server
  - docker build -t pepperoniblvd/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push pepperoniblvd/multi-client
  - docker push pepperoniblvd/multi-nginx
  - docker push pepperoniblvd/multi-server
  - docker push pepperoniblvd/multi-worker
